# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/work/BackupWork/NewAllGo

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/work/BackupWork/NewAllGo

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/work/BackupWork/NewAllGo/CMakeFiles /home/work/BackupWork/NewAllGo/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/work/BackupWork/NewAllGo/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named libfaunus

# Build rule for target.
libfaunus: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libfaunus
.PHONY : libfaunus

# fast build rule for target.
libfaunus/fast:
	$(MAKE) -f src/CMakeFiles/libfaunus.dir/build.make src/CMakeFiles/libfaunus.dir/build
.PHONY : libfaunus/fast

#=============================================================================
# Target rules for targets named docopt

# Build rule for target.
docopt: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 docopt
.PHONY : docopt

# fast build rule for target.
docopt/fast:
	$(MAKE) -f src/CMakeFiles/docopt.dir/build.make src/CMakeFiles/docopt.dir/build
.PHONY : docopt/fast

#=============================================================================
# Target rules for targets named xdrfile

# Build rule for target.
xdrfile: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 xdrfile
.PHONY : xdrfile

# fast build rule for target.
xdrfile/fast:
	$(MAKE) -f src/xdrfile/CMakeFiles/xdrfile.dir/build.make src/xdrfile/CMakeFiles/xdrfile.dir/build
.PHONY : xdrfile/fast

#=============================================================================
# Target rules for targets named example_membrane

# Build rule for target.
example_membrane: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 example_membrane
.PHONY : example_membrane

# fast build rule for target.
example_membrane/fast:
	$(MAKE) -f src/examples/CMakeFiles/example_membrane.dir/build.make src/examples/CMakeFiles/example_membrane.dir/build
.PHONY : example_membrane/fast

#=============================================================================
# Target rules for targets named example_stripes

# Build rule for target.
example_stripes: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 example_stripes
.PHONY : example_stripes

# fast build rule for target.
example_stripes/fast:
	$(MAKE) -f src/examples/CMakeFiles/example_stripes.dir/build.make src/examples/CMakeFiles/example_stripes.dir/build
.PHONY : example_stripes/fast

#=============================================================================
# Target rules for targets named example_stockmayer

# Build rule for target.
example_stockmayer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 example_stockmayer
.PHONY : example_stockmayer

# fast build rule for target.
example_stockmayer/fast:
	$(MAKE) -f src/examples/CMakeFiles/example_stockmayer.dir/build.make src/examples/CMakeFiles/example_stockmayer.dir/build
.PHONY : example_stockmayer/fast

#=============================================================================
# Target rules for targets named example_potfromfile

# Build rule for target.
example_potfromfile: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 example_potfromfile
.PHONY : example_potfromfile

# fast build rule for target.
example_potfromfile/fast:
	$(MAKE) -f src/examples/CMakeFiles/example_potfromfile.dir/build.make src/examples/CMakeFiles/example_potfromfile.dir/build
.PHONY : example_potfromfile/fast

#=============================================================================
# Target rules for targets named example_gcmol

# Build rule for target.
example_gcmol: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 example_gcmol
.PHONY : example_gcmol

# fast build rule for target.
example_gcmol/fast:
	$(MAKE) -f src/examples/CMakeFiles/example_gcmol.dir/build.make src/examples/CMakeFiles/example_gcmol.dir/build
.PHONY : example_gcmol/fast

#=============================================================================
# Target rules for targets named example_spheresurface

# Build rule for target.
example_spheresurface: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 example_spheresurface
.PHONY : example_spheresurface

# fast build rule for target.
example_spheresurface/fast:
	$(MAKE) -f src/examples/CMakeFiles/example_spheresurface.dir/build.make src/examples/CMakeFiles/example_spheresurface.dir/build
.PHONY : example_spheresurface/fast

#=============================================================================
# Target rules for targets named example_gctit

# Build rule for target.
example_gctit: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 example_gctit
.PHONY : example_gctit

# fast build rule for target.
example_gctit/fast:
	$(MAKE) -f src/examples/CMakeFiles/example_gctit.dir/build.make src/examples/CMakeFiles/example_gctit.dir/build
.PHONY : example_gctit/fast

#=============================================================================
# Target rules for targets named unittests

# Build rule for target.
unittests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 unittests
.PHONY : unittests

# fast build rule for target.
unittests/fast:
	$(MAKE) -f src/examples/CMakeFiles/unittests.dir/build.make src/examples/CMakeFiles/unittests.dir/build
.PHONY : unittests/fast

#=============================================================================
# Target rules for targets named example_water2

# Build rule for target.
example_water2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 example_water2
.PHONY : example_water2

# fast build rule for target.
example_water2/fast:
	$(MAKE) -f src/examples/CMakeFiles/example_water2.dir/build.make src/examples/CMakeFiles/example_water2.dir/build
.PHONY : example_water2/fast

#=============================================================================
# Target rules for targets named example_penalty

# Build rule for target.
example_penalty: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 example_penalty
.PHONY : example_penalty

# fast build rule for target.
example_penalty/fast:
	$(MAKE) -f src/examples/CMakeFiles/example_penalty.dir/build.make src/examples/CMakeFiles/example_penalty.dir/build
.PHONY : example_penalty/fast

#=============================================================================
# Target rules for targets named example_minimal

# Build rule for target.
example_minimal: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 example_minimal
.PHONY : example_minimal

# fast build rule for target.
example_minimal/fast:
	$(MAKE) -f src/examples/CMakeFiles/example_minimal.dir/build.make src/examples/CMakeFiles/example_minimal.dir/build
.PHONY : example_minimal/fast

#=============================================================================
# Target rules for targets named example_cigars2fibrils

# Build rule for target.
example_cigars2fibrils: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 example_cigars2fibrils
.PHONY : example_cigars2fibrils

# fast build rule for target.
example_cigars2fibrils/fast:
	$(MAKE) -f src/examples/CMakeFiles/example_cigars2fibrils.dir/build.make src/examples/CMakeFiles/example_cigars2fibrils.dir/build
.PHONY : example_cigars2fibrils/fast

#=============================================================================
# Target rules for targets named example_grand

# Build rule for target.
example_grand: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 example_grand
.PHONY : example_grand

# fast build rule for target.
example_grand/fast:
	$(MAKE) -f src/examples/CMakeFiles/example_grand.dir/build.make src/examples/CMakeFiles/example_grand.dir/build
.PHONY : example_grand/fast

#=============================================================================
# Target rules for targets named example_water2_ewald

# Build rule for target.
example_water2_ewald: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 example_water2_ewald
.PHONY : example_water2_ewald

# fast build rule for target.
example_water2_ewald/fast:
	$(MAKE) -f src/examples/CMakeFiles/example_water2_ewald.dir/build.make src/examples/CMakeFiles/example_water2_ewald.dir/build
.PHONY : example_water2_ewald/fast

#=============================================================================
# Target rules for targets named example_bulk

# Build rule for target.
example_bulk: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 example_bulk
.PHONY : example_bulk

# fast build rule for target.
example_bulk/fast:
	$(MAKE) -f src/examples/CMakeFiles/example_bulk.dir/build.make src/examples/CMakeFiles/example_bulk.dir/build
.PHONY : example_bulk/fast

#=============================================================================
# Target rules for targets named example_slitpolymer

# Build rule for target.
example_slitpolymer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 example_slitpolymer
.PHONY : example_slitpolymer

# fast build rule for target.
example_slitpolymer/fast:
	$(MAKE) -f src/examples/CMakeFiles/example_slitpolymer.dir/build.make src/examples/CMakeFiles/example_slitpolymer.dir/build
.PHONY : example_slitpolymer/fast

#=============================================================================
# Target rules for targets named example_capparticles

# Build rule for target.
example_capparticles: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 example_capparticles
.PHONY : example_capparticles

# fast build rule for target.
example_capparticles/fast:
	$(MAKE) -f src/examples/CMakeFiles/example_capparticles.dir/build.make src/examples/CMakeFiles/example_capparticles.dir/build
.PHONY : example_capparticles/fast

#=============================================================================
# Target rules for targets named example_polymers

# Build rule for target.
example_polymers: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 example_polymers
.PHONY : example_polymers

# fast build rule for target.
example_polymers/fast:
	$(MAKE) -f src/examples/CMakeFiles/example_polymers.dir/build.make src/examples/CMakeFiles/example_polymers.dir/build
.PHONY : example_polymers/fast

#=============================================================================
# Target rules for targets named example_keesom

# Build rule for target.
example_keesom: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 example_keesom
.PHONY : example_keesom

# fast build rule for target.
example_keesom/fast:
	$(MAKE) -f src/examples/CMakeFiles/example_keesom.dir/build.make src/examples/CMakeFiles/example_keesom.dir/build
.PHONY : example_keesom/fast

#=============================================================================
# Target rules for targets named example_stockmayer_polarizable

# Build rule for target.
example_stockmayer_polarizable: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 example_stockmayer_polarizable
.PHONY : example_stockmayer_polarizable

# fast build rule for target.
example_stockmayer_polarizable/fast:
	$(MAKE) -f src/examples/CMakeFiles/example_stockmayer_polarizable.dir/build.make src/examples/CMakeFiles/example_stockmayer_polarizable.dir/build
.PHONY : example_stockmayer_polarizable/fast

#=============================================================================
# Target rules for targets named example_bulk_coulomb

# Build rule for target.
example_bulk_coulomb: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 example_bulk_coulomb
.PHONY : example_bulk_coulomb

# fast build rule for target.
example_bulk_coulomb/fast:
	$(MAKE) -f src/examples/CMakeFiles/example_bulk_coulomb.dir/build.make src/examples/CMakeFiles/example_bulk_coulomb.dir/build
.PHONY : example_bulk_coulomb/fast

#=============================================================================
# Target rules for targets named example_bulk_dh

# Build rule for target.
example_bulk_dh: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 example_bulk_dh
.PHONY : example_bulk_dh

# fast build rule for target.
example_bulk_dh/fast:
	$(MAKE) -f src/examples/CMakeFiles/example_bulk_dh.dir/build.make src/examples/CMakeFiles/example_bulk_dh.dir/build
.PHONY : example_bulk_dh/fast

#=============================================================================
# Target rules for targets named example_twobody

# Build rule for target.
example_twobody: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 example_twobody
.PHONY : example_twobody

# fast build rule for target.
example_twobody/fast:
	$(MAKE) -f src/examples/CMakeFiles/example_twobody.dir/build.make src/examples/CMakeFiles/example_twobody.dir/build
.PHONY : example_twobody/fast

#=============================================================================
# Target rules for targets named example_cigarsenergy

# Build rule for target.
example_cigarsenergy: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 example_cigarsenergy
.PHONY : example_cigarsenergy

# fast build rule for target.
example_cigarsenergy/fast:
	$(MAKE) -f src/examples/CMakeFiles/example_cigarsenergy.dir/build.make src/examples/CMakeFiles/example_cigarsenergy.dir/build
.PHONY : example_cigarsenergy/fast

#=============================================================================
# Target rules for targets named pyfaunus

# Build rule for target.
pyfaunus: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pyfaunus
.PHONY : pyfaunus

# fast build rule for target.
pyfaunus/fast:
	$(MAKE) -f scripts/CMakeFiles/pyfaunus.dir/build.make scripts/CMakeFiles/pyfaunus.dir/build
.PHONY : pyfaunus/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... test"
	@echo "... libfaunus"
	@echo "... docopt"
	@echo "... xdrfile"
	@echo "... example_membrane"
	@echo "... example_stripes"
	@echo "... example_stockmayer"
	@echo "... example_potfromfile"
	@echo "... example_gcmol"
	@echo "... example_spheresurface"
	@echo "... example_gctit"
	@echo "... unittests"
	@echo "... example_water2"
	@echo "... example_penalty"
	@echo "... example_minimal"
	@echo "... example_cigars2fibrils"
	@echo "... example_grand"
	@echo "... example_water2_ewald"
	@echo "... example_bulk"
	@echo "... example_slitpolymer"
	@echo "... example_capparticles"
	@echo "... example_polymers"
	@echo "... example_keesom"
	@echo "... example_stockmayer_polarizable"
	@echo "... example_bulk_coulomb"
	@echo "... example_bulk_dh"
	@echo "... example_twobody"
	@echo "... example_cigarsenergy"
	@echo "... pyfaunus"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

